#!/bin/bash
# Read user input and store it in the varibale 'num1'
read -p "Enter the first number:" num1
# Read user input and store it in the variable 'num2'
read -p "Enter the second number" num2

# Compare the two numbers
if [ $num1 -eq $num2 ];then
        echo "Both numbers are equal."
elif [ $num1 -lt $num2 ]; then
        echo "$num1 is less than $num2."
else
        echo "$num1 is greater than $num2."
fi
